pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - script: |
            git config --global user.email "youtname@yourdomain.de"
            git config --global user.name "yourusername"
            sudo apt-get install texlive texlive-lang-german texlive-latex-extra
            sudo apt-get install texlive-bibtex-extra
            sudo apt-get install texlive-font-utils
            sudo wget http://mirrors.ctan.org/macros/latex/contrib/titlesec/titlesec.sty -O /usr/share/texlive/texmf-dist/tex/latex/titlesec/titlesec.sty
            pdflatex -synctex=1 -interaction=nonstopmode  -halt-on-error Expose.tex 
            bibtex Expose
            pdflatex -synctex=1 -interaction=nonstopmode -halt-on-error Expose.tex 
            pdflatex -synctex=1 -interaction=nonstopmode -halt-on-error Expose.tex
            pdflatex -synctex=1 -interaction=nonstopmode -halt-on-error Expose.tex
            git add Expose.pdf
            git commit -m "LaTex Compiled2Pdf with Azure-Pipelines"
            git push origin HEAD:master
    displayName: 'Latex'
